
python_distribution(
    name="pkg",
    dependencies=[
         "./templates:tmpl",  # templates
        "./src/minimal:lib",  # sources
    ],
    provides=python_artifact(name="minimal", version="0.0.1"),
    generate_setup=True,
)

